### ISSUE TITLE
dev-mongo branch todo's

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudlaunch#50]
This is relation to https://github.com/galaxyproject/cloudlaunch/issues/49 as one possible avenue for implementing the new launcher. This branch is based on the following stack: [Django](https://www.djangoproject.com/), [Django Rest Framework](http://www.django-rest-framework.org/), [MongoDB](https://www.mongodb.com/), [Django Rest Framework Mongoengine](https://pythonhosted.org/django-rest-framework-mongoengine/). The following is a fluid list of current tasks:

- [ ] Figure out how to `POST` a nested field (e.g., an `Application` with a `Category`)
- [ ] Define the models
- [ ] Integrate [Django Social Auth](https://django-social-auth.readthedocs.org/en/latest/)
- [ ] Setup testing with Travis
- [ ] Write setup docs
- [ ] Decide how the Admin side of things will be handled given no default Django Admin site
- [ ] Add a Celery task queue

**Comment by afgane** [comment]
After experimenting with the specified software stack, a conclusion was that much of those projects are in flux, have very limited documentation, and they don't necessarily integrate well with one another re. support for their native features. With that, a decision was made not to pursue this avenue for the time being and revert to the relational model. See https://github.com/galaxyproject/cloudlaunch/issues/52 and the [dev](https://github.com/galaxyproject/cloudlaunch/tree/dev) branch for more on that effort.
