### ISSUE TITLE
dev branch todo's

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudlaunch#52]
This is relation to https://github.com/galaxyproject/cloudlaunch/issues/49 for implementing the new launcher. This branch is based on the following stack: [Django](https://www.djangoproject.com/), [Django Rest Framework](http://www.django-rest-framework.org/), [Django Social Auth](https://django-social-auth.readthedocs.org/en/latest/), [Celery](http://www.celeryproject.org/). The app is intended to supply a REST API without an embedded UI (the UI will be a developed as a separate project to consume the API). The following is a fluid list of current tasks:
- [x] Define the base app models
- [x] Add a Celery task queue
- [x] Decide if we want to use [DRF-Nested-Routers](https://github.com/alanjds/drf-nested-routers) for nicer URls
- [x] Do we want to use slugs or IDs for resources?
- [x] Define the following base API endpoints
  - [x] `/applications`
  - [x] `/deployments`
  - [x] `/infrastructure`
- [x] Stored credential encryption
- [x] Provide ability to retrieve credentials from request (directly through headers or perhaps through middleware)
- [x] Add OAuth support
- [ ] Tests and coverage
- [x] Implement support for POST requests to be able to create resources
- [x] Add support to track usage

**Comment by afgane** [comment]
[Celery 4.0](http://docs.celeryproject.org/en/master/whatsnew-4.0.html) will officially support Python 3.5; the 4.0 is at RC1 now so as we move along, it hopefully gets released but it's something to keep in mind.

**Comment by nuwang** [comment]
Slugs vs IDs for Resources - I guess we can decide on this based on the type of resource? Probably based on whether the user will want to understand/remember the slug or not. (background tasks could use the id for example)

DRF-nested-routers - I guess we are a yes on this?
